### ISSUE TITLE
Cardconnect Issues in opencart 3.0.2.0

### ISSUE THREAD

**Issue by Milomyth** [straightlight/opencart_contributions#1]
i getting this error trying enabling the extension

`Notice: Undefined index: payment_cardconnect_api_username in C:\xampp\htdocs\tienda\admin\controller\extension\payment\cardconnect.php on line 483Notice: Undefined index: payment_cardconnect_api_password in C:\xampp\htdocs\tienda\admin\controller\extension\payment\cardconnect.php on line 487Notice: Undefined index: payment_cardconnect_token in C:\xampp\htdocs\tienda\admin\controller\extension\payment\cardconnect.php on line 491Notice: Undefined index: payment_cardconnect_site in C:\xampp\htdocs\tienda\admin\controller\extension\payment\cardconnect.php on line 495`

im testing in localhost, it's my first time using opencart so i don't understand how the extension works

**Comment by straightlight** [comment]
This issue has been officially resolved on Opencart namespace.
