### ISSUE TITLE
PayPal

### ISSUE THREAD

**Issue by haxcop** [straightlight/opencart_contributions#2]
## Question
I saw your post on the forums but I do not know if this contribution recorded here on your repo will fix the current issues with PayPal Express and Standard. 

### With PayPal Express on the default theme and also with journal3

![b4bae990-0df5-4f77-9fa2-3232381e7cf6 (2)](https://user-images.githubusercontent.com/7826906/57864318-94e05980-77f3-11e9-8ed1-9ab1a73feaa6.png)

### With PayPal Standard
![image](https://user-images.githubusercontent.com/7826906/57864111-387d3a00-77f3-11e9-967d-b0f884ecb86b.png)

###  Opencart
`V. 3.0.3.2`
`php71`

**Comment by straightlight** [comment]
These changes are for the OC core, not for 3rd party extensions (using Journal!)
