### ISSUE TITLE
Paypal express checkout issue

### ISSUE THREAD

**Issue by auvilink** [straightlight/opencart_contributions#4]
Thanks for the good work!
I checked out the forum which led me to this repository.

My question is: 
Do I have the replace every file (over 200 files) in OC core (under **### mywebsie/putlic_html** folder)from the **### upload** folder for PayPal express checkout to work?

I currently got the following error:
Error: Error: There was an error fetching the PayPal token at eval (eval at globalEval (https://fancyally.com/catalog/view/javascript/jquery/jquery-2.1.1.min.js:2:2536), :22:21) at _loop (https://www.paypalobjects.com/api/checkout.js:774:46) at ZalgoPromise._proto.dispatch (https://www.paypalobjects.com/api/checkout.js:791:53) at ZalgoPromise._proto.resolve (https://www.paypalobjects.com/api/checkout.js:746:66) at https://www.paypalobjects.com/api/checkout.js:732:41 at XMLHttpRequest. (https://www.paypalobjects.com/api/checkout.js:1087:24) at Object._RECEIVE_MESSAGE_TYPE. [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:4170:27) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:4201:48) at messageListener (https://www.paypalobjects.com/api/checkout.js:4220:9)

Thank you.

Cheers.

**Comment by straightlight** [comment]
All the files involving the filename: pp_express must be replaced.

**Comment by auvilink** [comment]
1. I uninstalled the paypal express checkout extension.
2. I replaced all the files involving the filename: pp_express 
3. I refreshed modification as well as "dashboard, cache" 
4. I reinstalled paypal express checkout extention.
5.  I repeated step 3.
6. now I got this error when trying to edit paypal express checkout extension:
"Fatal error: Uncaught exception 'Exception' with message 'Error: Table 'fancyall_opencart.oc_paypal_zone' doesn't exist<br />Error No: 1146<br />SELECT *, `c`.`name` AS `country_name`, `z`.`name` AS `zone_name`, `z`.`code` AS `zone_code`, `pz`.`code` AS `paypal_code`, `pz`.`paypal_code` AS `ship_to_state` FROM `oc_paypal_zone` `pz` LEFT JOIN `oc_zone` `z` ON (`z`.`zone_id` = `pz`.`zone_id`) LEFT JOIN `oc_country` `c` ON (`c`.`country_id` = `z`.`country_id`) WHERE `z`.`country_id` = `pz`.`country_id` AND `pz`.`code` != `z`.`code` AND LENGTH(TRIM(`pz`.`code`)) > 0 AND LENGTH(TRIM(`z`.`code`)) > 0 AND `c`.`status` = '1' AND `z`.`status` = '1'' in /home3/fancyally/public_html/system/library/db/mysqli.php:40 Stack trace: #0 /home3/fancyally/public_html/system/library/db.php(45): DB\MySQLi->query('SELECT *, `c`.`...') #1 /home3/fancyally/public_html/admin/model/extension/payment/pp_express.php(430): DB->query('SELECT *, `c`.`...') #2 [internal function]: ModelExtensionPaymentPpExpress->getUnmatchedZoneCodes() #3 /home3/fancyall in /home3/fancyally/public_html/system/library/db/mysqli.php on line 40"


Any ideas? Thanks a lot.

**Comment by straightlight** [comment]
Ensure the system/helper/pp_express_zones.php file is also active. Otherwise, the database table won't be created.

**Comment by auvilink** [comment]
> Ensure the system/helper/pp_express_zones.php file is also active. Otherwise, the database table won't be created.

Sure enough, I did not add the "system/helper/pp_express_zones.php". Now the "Error: Table 'fancyall_opencart.oc_paypal_zone' doesn't exist" is gone.

I configured all paypal express checkout, retried the check out on the live website but still got the original errors showed below. Something must not be right.

**Error: Error: There was an error fetching the PayPal token at eval (eval at globalEval (https://fancyally.com/catalog/view/javascript/jquery/jquery-2.1.1.min.js:2:2536), :14:21) at _loop (https://www.paypalobjects.com/api/checkout.js:774:46) at ZalgoPromise._proto.dispatch (https://www.paypalobjects.com/api/checkout.js:791:53) at ZalgoPromise._proto.resolve (https://www.paypalobjects.com/api/checkout.js:746:66) at https://www.paypalobjects.com/api/checkout.js:732:41 at XMLHttpRequest. (https://www.paypalobjects.com/api/checkout.js:1087:24) at Object._RECEIVE_MESSAGE_TYPE. [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:4171:27) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:4202:48) at messageListener (https://www.paypalobjects.com/api/checkout.js:4221:9)**

**Comment by straightlight** [comment]
Use your developers kit and check the error / server access logs. More information is needed.

**Comment by auvilink** [comment]
2019-05-26 21:52:57 - PHP Notice:  Undefined index: TOKEN in /home3/fancyally/public_html/catalog/controller/extension/payment/pp_express.php on line 1638
2019-05-26 21:52:57 - PHP Warning:  Cannot modify header information - headers already sent by (output started at /home3/fancyally/public_html/catalog/controller/startup/error.php:34) in /home3/fancyally/public_html/system/library/response.php on line 36
2019-05-26 21:53:57 - PHP Notice:  Undefined index: TOKEN in /home3/fancyally/public_html/catalog/controller/extension/payment/pp_express.php on line 1638
2019-05-26 21:53:57 - PHP Warning:  Cannot modify header information - headers already sent by (output started at /home3/fancyally/public_html/catalog/controller/startup/error.php:34) in /home3/fancyally/public_html/system/library/response.php on line 36

**Comment by straightlight** [comment]
This issue is caused by an invalid login and / or password from your API credentials. Ensure to enter them correctly. Also, which OC version are you using and do you use the PP login seamless module to login with your access identity token?

**Comment by auvilink** [comment]
I am using the latest OC 3.0.3.2.
I used the PP live configuration and it seems success as shown in the attached file.
<img width="461" alt="Paypal_Authorize" src="https://user-images.githubusercontent.com/13460230/58390487-56625000-7fe6-11e9-81d1-9f99be41882f.png">

**Comment by straightlight** [comment]
PayPal live of what? PP Seamless or the API username & API password? More information is needed!

**Comment by auvilink** [comment]
<img width="1000" alt="PP_live" src="https://user-images.githubusercontent.com/13460230/58390640-18196080-7fe7-11e9-9a2c-53f817456435.png">

**Comment by straightlight** [comment]
Insufficient. Are you using an API username & API password with your live account or are you using a seamless login?

**Comment by auvilink** [comment]
I do not know how to do a seamless login. I used API username & password with live paypal account.
All xxx are replaced with real live paypal account api credentials.
<img width="1032" alt="PP_API" src="https://user-images.githubusercontent.com/13460230/58390759-b5749480-7fe7-11e9-95c2-2c6474bb82f8.png">

**Comment by auvilink** [comment]
However, in my Paypal live account, I only see following, which I am not sure if it is from opencart.
<img width="915" alt="PP_third-party" src="https://user-images.githubusercontent.com/13460230/58390792-db9a3480-7fe7-11e9-91af-a3e5e9d142f3.png">

**Comment by straightlight** [comment]
Ensure that the same API username and API password are being used as the one generated from your PayPal's merchant account. TOKEN error means that your API account with your PayPal Merchant's account is not configured properly.

**Comment by auvilink** [comment]
Just want to make sure API Signature in Opencart is the same as API fingerprint in Paypal live account, right?

**Comment by straightlight** [comment]
This section is not to learn how to configure PayPal. It is for patch troubleshooting. Since there's nothing wrong with the modifications itself, this topic will now be closed.

**Comment by auvilink** [comment]
I used the same API from Paypal live account as shown below for the configuration, which I think is the right way.
<img width="1143" alt="PP_API_F" src="https://user-images.githubusercontent.com/13460230/58391178-8101d800-7fe9-11e9-9cd5-ca6df3a33bc6.png">
