### ISSUE TITLE
Does the Paypal fix work for Journal 3

### ISSUE THREAD

**Issue by Ashon95** [straightlight/opencart_contributions#6]
do i upload all files from this and reinstall paypal also does this work for journal ??

**Comment by petp3t** [comment]
no doesn't work on journal 3

**Comment by atnaples** [comment]
There is no word "fix" in OpenCart team's vocabulary as there is no standard. All fixes are new version for new OpenCart full of ... new bugs.

OpenCart 3.0.3.2 for "US market":
- UPS does not work
- FedEx does not work
- US Mail has a bug (for ages)
- PayPal Standard has a bug
etc.

What are we talking about? "FIXES"?

**Comment by straightlight** [comment]
Unsupported claim. Closing issue.
